# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MMS-Mail-Parser
version:      0.09
version_from: lib/MMS/Mail/Parser.pm
installdirs:  site
requires:
    Class::Accessor:               0.19
    MIME::Parser:                  5.4
    MMS::Mail::Message:            0.05
    MMS::Mail::Message::Parsed:    0.06
    MMS::Mail::Provider:           0.06
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
